name: ably_flutter_integration_test
description: Integration tests for Ably Flutter plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.6.0
  ably_flutter:
    path: '..'
  ably_flutter_example:
    path: '../example'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ^0.12.2
  test: ^1.9.4

flutter:
  uses-material-design: true
