name: ably_flutter_integration_test
description: Integration tests for Ably Flutter plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ably_flutter:
    path: '..'
  ably_flutter_example:
    path: '../example'
  args: ^2.0.0
  flutter:
    sdk: flutter
  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: 1.16.7

flutter:
  uses-material-design: true
