name: ably_flutter_example
description: Demonstrates how to use the Ably Flutter plugin.
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  retry: ^3.0.1

dev_dependencies:
  ably_flutter:
    path: ../
  flutter_test:
    sdk: flutter

  # Stricter Linting
  pedantic: ^1.0.0

flutter:
  uses-material-design: true
